# Generated by Django 2.0.5 on 2019-09-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_to', '0002_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obj',
            name='сustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust', to='app_to.Customers'),
        ),
    ]
